version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory_db
      REDIS_HOST: redis
      JWT_SECRET: f10ab2c49da13f8b06f18d393aa743363227b2a4f46726c6967a105c5c987ce85d73d4681fa7912de34cc8510992690ccae35f879c3904d74024fd58574b5a12

  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend